name: Build and Greet using Environment Variables
on: push
env:
  Global_Message: 'Global message MGT44'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: python -c "print(f'${Global_Message}')"
  greet:
    runs-on: ubuntu-latest
    env:
      Greeting_Message: 'Greeting message MGT3'  
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: python -c "print(f'${Greeting_Message}')"

